language: node_js
node_js:
  - 8
  - 9
services: redis
# this runs eslint, runs the tests, instruments their coverage, and
# publishes it to coveralls.io
script: npm run ci
after_script:
  - redis-cli script flush

# Don't build pushes to branches other than master. This doesn’t affect pull-
# request builds, which are separate from branch builds in Travis.
branches:
  only:
    - master
