version: '3.7'

services:

  # Run ping.js in a container created from our image
  ping:
    build: .
    command: node ping.js

  # Run pong.js in a container created from our image
  pong:
    build: .
    command: node pong.js


  # Run Redis in a container created from the redis:alpine image from Docker Hub
  redis:
    image: redis:alpine
    command: redis-server --tcp-backlog 128 --logfile /dev/null
